Docs updated
cernbox/file-picker-docs pull request #2
Opened 2023-07-12 14:29 UTC by AleksaMCode

2023-07-12 19:29 UTC, avivace requested changes
Thanks @AleksaMCode !

Before flagging this as ready (and ask @javfg to give a review) branch should be rebased.

2023-07-12 19:29 UTC, avivace commented on content/setup/_index.md
> +	# location of the build of file-picker
I think indentation here should be fixed to use space like the rest of the document

2023-07-12 19:29 UTC, avivace commented on content/setup/_index.md
> +    server_name YOURHOSTNAME;
indent here is 4 spaces, correct to 2
```suggestion
  server_name YOURHOSTNAME;
```

2023-07-12 19:29 UTC, avivace commented on content/setup/_index.md
> +    # hostname we will be serving on, e.g. localhost
```suggestion
  # hostname we will be serving on, e.g. localhost
```

2023-07-12 19:29 UTC, avivace commented on content/setup/_index.md
> +This guide has been tested in CentOS 7, Ubuntu 22.04 and Linux Mint 21.1, but it should work in
Linux Mint is based on Ubuntu, I don't think they are different enough to deserve to be distinguished here

2023-07-13 07:01 UTC, javfg commented
Thanks for the contribution! :tada:

I think @avivace review covers most of it, I just added a small detail. Should be ready to merge as soon as those are fixed.

2023-07-13 09:06 UTC, avivace commented
@javfg Thanks for taking a look! We just noticed that the Hugo build is not in the pipeline (so after merging nothing will change https://filepicker.cernbox.cern.ch/docs, I guess). Should we commit changes to public too? Or you want to do that once we marge the changes on the src?

2023-07-13 11:20 UTC, javfg commented
Ah yup, please add the new build! I'll set up a proper pipeline when I have some free time. :)

2023-07-25 10:01 UTC, javfg commented
No need to review this changes, as it is an update of the theme used in the docs.

2023-07-25 10:05 UTC, merged